import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const AeonikTRIAL = localFont({
  src: [
    {
      path: "../public/fonts/AeonikTRIAL-Regular.otf",
      weight: "400",
      style: "normal",
    },

    {
      path: '../public/fonts/AeonikTRIAL-Bold.otf',
      weight: '700',
      style: 'bold',
    },
  ],
});

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Analytics />
      </body>
    </html>
  );
}
